### PR TITLE
Bump version to 0.4.3

### PR DESCRIPTION
**Pull request by xaionaro**
@barak hello!

If there's some extra time then it would be great to update the version of `clsync`. If I can help somehow then please let me know.

I've also (temporary) disabled seccomp to bypass the problem:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844778

I really appreciative your maintainer's work and if I can free your time on maintaining other packages then I would like to be useful: just give me a task.

Thank you :)

### CODE REVIEW

**Comment by barak** [comment]
Okay, building it now.
I tagged `b58aa36` as `upstream/0.4.3` to generate a tarball, you should probably tag that as `v0.4.3`.
At some point we should use a separate branch for the debian stuff, etc.

**Comment by barak** [comment]
Built package uploaded to debian.

Alright I made a separate debian branch, enjoy! Pulled the `debian/` subdir out of branch `master`, and pushed both branches to your repo.

You've been using debian/changelog to record both debian packaging and upstream changes.
Really the upstream changelog belongs in its own file. Named `CHANGELOG` or something like that.
We should migrate info out of debian/changelog and into that new file...

**Comment by xaionaro** [comment]
Thank you!

> You've been using debian/changelog to record both debian packaging and upstream changes.
> Really the upstream changelog belongs in its own file. Named CHANGELOG or something like that.
> We should migrate info out of debian/changelog and into that new file...

OK. Will be fixed.

**Comment by xaionaro** [comment]
I've tagged e367cf0 as `v0.4.3`. And it's required to use this comment. I just noticed the problem with seccomp in Debian's ITS after commit b58aa36 :(

**Comment by barak** [comment]
Okay. The version I uploaded had the change you tagged. The skew in our tags or consequent "upstream" tarball delta will not make any difference in the generated binaries, so I don't see any need to reconcile them.

**Pull request merged**
